Created two additional python test files for the USR2 and USR3 onboar…
Senior-Design-0x07/the-hobby-hub pull request #22
Opened 2020-12-14 21:13 UTC by iliescua

…d LEDs

# Date
12/14/2020
Initial PR Date:
12/14/2020
Due Date: 

# Reviewers
@rockboynton 

# Description
Created two more python test files for LED USR2 and USR3 so now all the onboard LEDs are accessible. 

# Project Issue
[Create Test "user programs" #9](https://github.com/Senior-Design-0x07/the-hobby-hub/issues/9)

# Test Results
Verified because all of the LEDs flash as expected when their subsequent file is run.

2020-12-14 21:45 UTC, rockboynton requested changes

2020-12-14 21:45 UTC, rockboynton commented on files/test_programs/light2.py
> +USR1_LED = "USR2"
Fix naming

2020-12-14 21:45 UTC, rockboynton commented on files/test_programs/light3.py
> +USR1_LED = "USR3"
Fix naming

2020-12-14 22:00 UTC, iliescua commented
Fixed it

2020-12-14 23:07 UTC, Ivendrakeo commented
Looks good to me. Assuming its good for you, rock merge it.

2020-12-15 05:51 UTC, rockboynton commented
😊

2020-12-15 05:52 UTC, merged